package cn.huan.kindergarten.dto;

/**Auto Generated By HTed Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.huan.HTed.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.huan.HTed.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "kg_assessment_activity_user_upload")
public class KgAssessmentActivityUserUpload extends BaseDTO {

     public static final String FIELD_ID = "progress_id";
     public static final String FIELD_UPLOAD_USER_ID = "uploadUserId";
     public static final String FIELD_ASSESSMENT_ACTIVITY_ID = "assessmentActivityId";
     public static final String FIELD_FILE_PATH = "filePath";

     
     private Long progress_id;

     @Length(max = 19)
     private Long uploadUserId;

     @Length(max = 19)
     private Long assessmentActivityId;

     @Length(max = 240)
     private String filePath;



     public Long getProgress_id() {
		return progress_id;
	}

	public void setProgress_id(Long progress_id) {
		this.progress_id = progress_id;
	}

	public void setUploadUserId(Long uploadUserId){
         this.uploadUserId = uploadUserId;
     }

     public Long getUploadUserId(){
         return uploadUserId;
     }

     public void setAssessmentActivityId(Long assessmentActivityId){
         this.assessmentActivityId = assessmentActivityId;
     }

     public Long getAssessmentActivityId(){
         return assessmentActivityId;
     }

     public void setFilePath(String filePath){
         this.filePath = filePath;
     }

     public String getFilePath(){
         return filePath;
     }

     }
